import request from '@/utils/request';

/**
 * 获取当前登录用户的个人信息/菜单/权限/角色
 */
export async function getUserInfo() {
  const res = await request.get('/system/auth/user');

  console.log("获取当前登录用户的个人信息/菜单/权限/角色");
  console.log(res);

  if (res.data.code === 200 && res.data.data) {
    return res.data.data;
    return {
      "userId": 1,
      "username": "admin",
      "password": "$2a$10$sWH.qQmf/dHMURzE4kN0puBOdB7VWwcDFB2NvwpMaHYz6OFZwQGBy",
      "nickname": "管理员",
      "avatar": "https://cdn.eleadmin.com/20200610/avatar.jpg",
      "sex": "1",
      "phone": "12345678901",
      "email": "eleadmin@eclouds.com",
      "emailVerified": 0,
      "realName": null,
      "idCard": null,
      "birthday": "2021-05-21",
      "introduction": "遗其欲，则心静！",
      "organizationId": 1,
      "status": 0,
      "deleted": 0,
      "tenantId": 1,
      "createTime": "2020-01-13 14:43:52",
      "updateTime": "2024-10-11 09:47:53",
      "organizationName": "XXX公司",
      "sexName": "男",
      "roles": [
          {
              "roleId": 1,
              "roleCode": "admin",
              "roleName": "管理员",
              "comments": "最高管理员",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-02-26 15:18:37",
              "updateTime": "2024-10-14 00:31:09",
              "userId": null
          }
      ],
      "authorities": [
          {
              "menuId": 36,
              "parentId": 0,
              "title": "仪表板",
              "path": "/dashboard",
              "component": null,
              "menuType": 0,
              "sortNumber": 0,
              "authority": null,
              "icon": "House",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:00:34",
              "updateTime": "2024-10-11 21:38:02",
              "children": null,
              "checked": null
          },
          {
              "menuId": 30,
              "parentId": 29,
              "title": "上传文件",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 1,
              "authority": "sys:file:upload",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-09-17 23:21:04",
              "updateTime": "2022-07-20 16:40:21",
              "children": null,
              "checked": null
          },
          {
              "menuId": 3,
              "parentId": 2,
              "title": "查询用户",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 1,
              "authority": "sys:user:list",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-02-26 12:52:06",
              "updateTime": "2020-09-16 11:05:35",
              "children": null,
              "checked": null
          },
          {
              "menuId": 8,
              "parentId": 7,
              "title": "查询角色",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 1,
              "authority": "sys:role:list",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-13 13:30:41",
              "updateTime": "2020-03-21 18:45:34",
              "children": null,
              "checked": null
          },
          {
              "menuId": 100,
              "parentId": 99,
              "title": "套餐管理",
              "path": "/vip/valueadded",
              "component": "/vip/valueadded",
              "menuType": 0,
              "sortNumber": 1,
              "authority": null,
              "icon": "Ticket",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:15:18",
              "updateTime": "2024-11-01 10:15:51",
              "children": null,
              "checked": null
          },
          {
              "menuId": 166,
              "parentId": 101,
              "title": "订单管理",
              "path": "/order/orderlist",
              "component": "",
              "menuType": 0,
              "sortNumber": 1,
              "authority": "",
              "icon": "GoodsFilled",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 01:18:37",
              "updateTime": "2024-11-01 10:16:05",
              "children": null,
              "checked": null
          },
          {
              "menuId": 140,
              "parentId": 163,
              "title": "模板管理",
              "path": "/templateplugin/template",
              "component": null,
              "menuType": 0,
              "sortNumber": 1,
              "authority": null,
              "icon": "DataAnalysis",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-11 21:32:11",
              "updateTime": "2024-11-01 10:16:19",
              "children": null,
              "checked": null
          },
          {
              "menuId": 164,
              "parentId": 152,
              "title": "笔记发布管理",
              "path": "/release/notespublicly",
              "component": "",
              "menuType": 0,
              "sortNumber": 1,
              "authority": "",
              "icon": "Compass",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:57:59",
              "updateTime": "2024-11-01 10:16:31",
              "children": null,
              "checked": null
          },
          {
              "menuId": 23,
              "parentId": 22,
              "title": "查询字典",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 1,
              "authority": "sys:dict:list",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:27",
              "updateTime": "2020-03-21 18:44:42",
              "children": null,
              "checked": null
          },
          {
              "menuId": 37,
              "parentId": 36,
              "title": "工作台",
              "path": "/dashboard/workplace",
              "component": "/dashboard/workplace",
              "menuType": 0,
              "sortNumber": 1,
              "authority": null,
              "icon": "el-icon-monitor",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:00:37",
              "updateTime": "2021-11-05 16:36:59",
              "children": null,
              "checked": null
          },
          {
              "menuId": 18,
              "parentId": 17,
              "title": "查询机构",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 1,
              "authority": "sys:org:list",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:21",
              "updateTime": "2020-03-21 18:44:36",
              "children": null,
              "checked": null
          },
          {
              "menuId": 158,
              "parentId": 157,
              "title": "客服中心",
              "path": "/feedback/customer",
              "component": "",
              "menuType": 0,
              "sortNumber": 1,
              "authority": "",
              "icon": "Service",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:16:43",
              "updateTime": "2024-11-01 10:16:53",
              "children": null,
              "checked": null
          },
          {
              "menuId": 155,
              "parentId": 154,
              "title": "隐私政策",
              "path": "/term/privacypolicy",
              "component": "",
              "menuType": 0,
              "sortNumber": 1,
              "authority": "",
              "icon": "ToiletPaper",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:13:26",
              "updateTime": "2024-11-01 10:17:07",
              "children": null,
              "checked": null
          },
          {
              "menuId": 2,
              "parentId": 1,
              "title": "系统用户管理",
              "path": "/system/user",
              "component": "/system/user",
              "menuType": 0,
              "sortNumber": 1,
              "authority": null,
              "icon": "el-icon-_user-group",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-02-26 12:51:55",
              "updateTime": "2024-10-14 00:28:09",
              "children": null,
              "checked": null
          },
          {
              "menuId": 62,
              "parentId": 61,
              "title": "我的资料",
              "path": "/user/profile",
              "component": "/user/profile",
              "menuType": 0,
              "sortNumber": 1,
              "authority": null,
              "icon": "el-icon-user",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:09:58",
              "updateTime": "2021-11-05 16:36:30",
              "children": null,
              "checked": null
          },
          {
              "menuId": 168,
              "parentId": 150,
              "title": "客户账户管理",
              "path": "/customer/user",
              "component": "/customer/user",
              "menuType": 0,
              "sortNumber": 1,
              "authority": "",
              "icon": "Avatar",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-11-01 10:13:21",
              "updateTime": "2024-11-01 10:58:17",
              "children": null,
              "checked": null
          },
          {
              "menuId": 153,
              "parentId": 130,
              "title": "笔记数据管理",
              "path": "/data/notesdata",
              "component": "",
              "menuType": 0,
              "sortNumber": 1,
              "authority": "",
              "icon": "MessageBox",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-13 23:08:46",
              "updateTime": "2024-11-01 10:15:30",
              "children": null,
              "checked": null
          },
          {
              "menuId": 13,
              "parentId": 12,
              "title": "查询菜单",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 1,
              "authority": "sys:menu:list",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 16:43:30",
              "updateTime": "2020-03-21 18:45:40",
              "children": null,
              "checked": null
          },
          {
              "menuId": 165,
              "parentId": 157,
              "title": "意见反馈中心",
              "path": "/feedback/opinion",
              "component": "",
              "menuType": 0,
              "sortNumber": 2,
              "authority": "",
              "icon": "InfoFilled",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 01:07:58",
              "updateTime": "2024-11-01 10:16:59",
              "children": null,
              "checked": null
          },
          {
              "menuId": 156,
              "parentId": 154,
              "title": "条件与条款",
              "path": "/term/conditionclause",
              "component": "",
              "menuType": 0,
              "sortNumber": 2,
              "authority": "",
              "icon": "Tickets",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:14:08",
              "updateTime": "2024-11-01 10:17:12",
              "children": null,
              "checked": null
          },
          {
              "menuId": 63,
              "parentId": 61,
              "title": "我的消息",
              "path": "/user/message",
              "component": "/user/message",
              "menuType": 0,
              "sortNumber": 2,
              "authority": null,
              "icon": "el-icon-chat-dot-round",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:10:03",
              "updateTime": "2021-11-05 16:36:27",
              "children": null,
              "checked": null
          },
          {
              "menuId": 169,
              "parentId": 150,
              "title": "客户统计分析",
              "path": "/customer/analysis",
              "component": "/customer/analysis",
              "menuType": 0,
              "sortNumber": 2,
              "authority": "",
              "icon": "Aim",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-11-01 10:19:51",
              "updateTime": "2024-11-01 10:58:38",
              "children": null,
              "checked": null
          },
          {
              "menuId": 161,
              "parentId": 130,
              "title": "文件存储管理",
              "path": "/data/file",
              "component": "",
              "menuType": 0,
              "sortNumber": 2,
              "authority": "",
              "icon": "MessageBox",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:30:22",
              "updateTime": "2024-11-01 10:15:37",
              "children": null,
              "checked": null
          },
          {
              "menuId": 14,
              "parentId": 12,
              "title": "添加菜单",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 2,
              "authority": "sys:menu:save",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 16:43:54",
              "updateTime": "2020-03-21 18:45:41",
              "children": null,
              "checked": null
          },
          {
              "menuId": 31,
              "parentId": 29,
              "title": "删除文件",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 2,
              "authority": "sys:file:remove",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-09-17 23:21:53",
              "updateTime": "2022-07-20 16:40:23",
              "children": null,
              "checked": null
          },
          {
              "menuId": 4,
              "parentId": 2,
              "title": "添加用户",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 2,
              "authority": "sys:user:save",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-02-26 12:52:26",
              "updateTime": "2020-03-21 18:45:29",
              "children": null,
              "checked": null
          },
          {
              "menuId": 9,
              "parentId": 7,
              "title": "添加角色",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 2,
              "authority": "sys:role:save",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-15 13:02:07",
              "updateTime": "2020-03-21 18:45:35",
              "children": null,
              "checked": null
          },
          {
              "menuId": 162,
              "parentId": 99,
              "title": "增值服务条款管理",
              "path": "/vip/term",
              "component": "",
              "menuType": 0,
              "sortNumber": 2,
              "authority": "",
              "icon": "Warning",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:48:10",
              "updateTime": "2024-11-01 10:15:57",
              "children": null,
              "checked": null
          },
          {
              "menuId": 167,
              "parentId": 101,
              "title": "订单统计",
              "path": "/order/statistics",
              "component": "",
              "menuType": 0,
              "sortNumber": 2,
              "authority": "",
              "icon": "PieChart",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 01:19:47",
              "updateTime": "2024-11-01 10:16:11",
              "children": null,
              "checked": null
          },
          {
              "menuId": 120,
              "parentId": 163,
              "title": "插件管理",
              "path": "/templateplugin/plugin",
              "component": null,
              "menuType": 0,
              "sortNumber": 2,
              "authority": null,
              "icon": "AppstoreAddOutlined",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-11 21:21:17",
              "updateTime": "2024-11-01 10:16:24",
              "children": null,
              "checked": null
          },
          {
              "menuId": 159,
              "parentId": 152,
              "title": "敏感词检测警告",
              "path": "/feedback/sensitive",
              "component": "",
              "menuType": 0,
              "sortNumber": 2,
              "authority": "",
              "icon": "QuestionFilled",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:17:33",
              "updateTime": "2024-11-01 10:16:36",
              "children": null,
              "checked": null
          },
          {
              "menuId": 24,
              "parentId": 22,
              "title": "添加字典",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 2,
              "authority": "sys:dict:save",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:28",
              "updateTime": "2020-03-21 18:45:59",
              "children": null,
              "checked": null
          },
          {
              "menuId": 38,
              "parentId": 36,
              "title": "分析页",
              "path": "/dashboard/analysis",
              "component": "/dashboard/analysis",
              "menuType": 0,
              "sortNumber": 2,
              "authority": null,
              "icon": "el-icon-data-analysis",
              "hide": 0,
              "meta": "{\"badge\": 1}",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:00:40",
              "updateTime": "2022-03-11 16:45:44",
              "children": null,
              "checked": null
          },
          {
              "menuId": 7,
              "parentId": 1,
              "title": "系统角色管理",
              "path": "/system/role",
              "component": "/system/role",
              "menuType": 0,
              "sortNumber": 2,
              "authority": null,
              "icon": "el-icon-postcard",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-13 13:29:08",
              "updateTime": "2024-10-14 00:28:15",
              "children": null,
              "checked": null
          },
          {
              "menuId": 19,
              "parentId": 17,
              "title": "添加机构",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 2,
              "authority": "sys:org:save",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:22",
              "updateTime": "2020-03-21 18:45:51",
              "children": null,
              "checked": null
          },
          {
              "menuId": 39,
              "parentId": 36,
              "title": "监控页",
              "path": "/dashboard/monitor",
              "component": "/dashboard/monitor",
              "menuType": 0,
              "sortNumber": 3,
              "authority": null,
              "icon": "el-icon-odometer",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:03:12",
              "updateTime": "2021-11-05 16:36:56",
              "children": null,
              "checked": null
          },
          {
              "menuId": 20,
              "parentId": 17,
              "title": "修改机构",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 3,
              "authority": "sys:org:update",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:24",
              "updateTime": "2020-03-21 18:45:52",
              "children": null,
              "checked": null
          },
          {
              "menuId": 151,
              "parentId": 130,
              "title": "数据备份",
              "path": "/data/databackup",
              "component": "",
              "menuType": 0,
              "sortNumber": 3,
              "authority": "",
              "icon": "MostlyCloudy",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-13 22:50:27",
              "updateTime": "2024-11-01 10:15:43",
              "children": null,
              "checked": null
          },
          {
              "menuId": 12,
              "parentId": 1,
              "title": "系统菜单管理",
              "path": "/system/menu",
              "component": "/system/menu",
              "menuType": 0,
              "sortNumber": 3,
              "authority": null,
              "icon": "el-icon-s-operation",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 01:07:13",
              "updateTime": "2024-10-14 00:28:40",
              "children": null,
              "checked": null
          },
          {
              "menuId": 15,
              "parentId": 12,
              "title": "修改菜单",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 3,
              "authority": "sys:menu:update",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:17",
              "updateTime": "2020-03-21 18:45:43",
              "children": null,
              "checked": null
          },
          {
              "menuId": 32,
              "parentId": 29,
              "title": "查看记录",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 3,
              "authority": "sys:file:list",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-09-17 23:20:29",
              "updateTime": "2022-07-20 16:40:24",
              "children": null,
              "checked": null
          },
          {
              "menuId": 5,
              "parentId": 2,
              "title": "修改用户",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 3,
              "authority": "sys:user:update",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-02-26 12:52:50",
              "updateTime": "2020-03-21 18:45:30",
              "children": null,
              "checked": null
          },
          {
              "menuId": 10,
              "parentId": 7,
              "title": "修改角色",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 3,
              "authority": "sys:role:update",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-15 13:02:49",
              "updateTime": "2020-03-21 18:45:36",
              "children": null,
              "checked": null
          },
          {
              "menuId": 25,
              "parentId": 22,
              "title": "修改字典",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 3,
              "authority": "sys:dict:update",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:29",
              "updateTime": "2020-03-21 18:46:01",
              "children": null,
              "checked": null
          },
          {
              "menuId": 160,
              "parentId": 152,
              "title": "敏感词库管理",
              "path": "/feedback/sensitivelibrary",
              "component": "",
              "menuType": 0,
              "sortNumber": 3,
              "authority": "",
              "icon": "DocumentRemove",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:24:12",
              "updateTime": "2024-11-01 10:16:41",
              "children": null,
              "checked": null
          },
          {
              "menuId": 6,
              "parentId": 2,
              "title": "删除用户",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 4,
              "authority": "sys:user:remove",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-02-26 12:53:13",
              "updateTime": "2020-03-21 18:45:32",
              "children": null,
              "checked": null
          },
          {
              "menuId": 11,
              "parentId": 7,
              "title": "删除角色",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 4,
              "authority": "sys:role:remove",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-20 17:58:51",
              "updateTime": "2020-03-21 18:45:38",
              "children": null,
              "checked": null
          },
          {
              "menuId": 17,
              "parentId": 1,
              "title": "机构管理",
              "path": "/system/organization",
              "component": "/system/organization",
              "menuType": 0,
              "sortNumber": 4,
              "authority": null,
              "icon": "el-icon-office-building",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:20",
              "updateTime": "2021-11-05 16:13:26",
              "children": null,
              "checked": null
          },
          {
              "menuId": 26,
              "parentId": 22,
              "title": "删除字典",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 4,
              "authority": "sys:dict:remove",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:31",
              "updateTime": "2020-03-21 18:46:02",
              "children": null,
              "checked": null
          },
          {
              "menuId": 21,
              "parentId": 17,
              "title": "删除机构",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 4,
              "authority": "sys:org:remove",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:25",
              "updateTime": "2020-03-21 18:45:54",
              "children": null,
              "checked": null
          },
          {
              "menuId": 16,
              "parentId": 12,
              "title": "删除菜单",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 4,
              "authority": "sys:menu:remove",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:18",
              "updateTime": "2020-03-21 18:45:44",
              "children": null,
              "checked": null
          },
          {
              "menuId": 33,
              "parentId": 2,
              "title": "用户详情",
              "path": "/system/user/details",
              "component": "/system/user/details",
              "menuType": 0,
              "sortNumber": 5,
              "authority": null,
              "icon": "el-icon-user",
              "hide": 1,
              "meta": "{\"active\": \"/system/user\"}",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-05-21 11:07:54",
              "updateTime": "2022-07-20 16:39:29",
              "children": null,
              "checked": null
          },
          {
              "menuId": 22,
              "parentId": 1,
              "title": "字典管理",
              "path": "/system/dictionary",
              "component": "/system/dictionary",
              "menuType": 0,
              "sortNumber": 5,
              "authority": null,
              "icon": "el-icon-notebook-2",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:26",
              "updateTime": "2021-11-05 16:13:30",
              "children": null,
              "checked": null
          },
          {
              "menuId": 29,
              "parentId": 1,
              "title": "文件管理",
              "path": "/system/file",
              "component": "/system/file",
              "menuType": 0,
              "sortNumber": 6,
              "authority": null,
              "icon": "el-icon-folder",
              "hide": 1,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-09-17 23:19:43",
              "updateTime": "2022-03-11 22:13:53",
              "children": null,
              "checked": null
          },
          {
              "menuId": 27,
              "parentId": 1,
              "title": "系统登录日志",
              "path": "/system/login-record",
              "component": "/system/login-record",
              "menuType": 0,
              "sortNumber": 7,
              "authority": "sys:login-record:list",
              "icon": "el-icon-date",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:33",
              "updateTime": "2024-10-14 00:28:26",
              "children": null,
              "checked": null
          },
          {
              "menuId": 28,
              "parentId": 1,
              "title": "系统操作日志",
              "path": "/system/operation-record",
              "component": "/system/operation-record",
              "menuType": 0,
              "sortNumber": 8,
              "authority": "sys:operation-record:list",
              "icon": "el-icon-_retrieve",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-03-21 18:24:34",
              "updateTime": "2024-10-14 00:28:31",
              "children": null,
              "checked": null
          },
          {
              "menuId": 34,
              "parentId": 1,
              "title": "修改个人密码",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 9,
              "authority": "sys:auth:password",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-09-17 23:22:45",
              "updateTime": "2022-07-20 16:40:53",
              "children": null,
              "checked": null
          },
          {
              "menuId": 35,
              "parentId": 1,
              "title": "修改个人资料",
              "path": null,
              "component": null,
              "menuType": 1,
              "sortNumber": 10,
              "authority": "sys:auth:user",
              "icon": null,
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-09-17 23:23:24",
              "updateTime": "2022-07-20 16:40:55",
              "children": null,
              "checked": null
          },
          {
              "menuId": 150,
              "parentId": 0,
              "title": "客户管理",
              "path": "/customer",
              "component": null,
              "menuType": 0,
              "sortNumber": 10,
              "authority": null,
              "icon": "User",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-11 21:34:48",
              "updateTime": "2024-11-01 10:58:04",
              "children": null,
              "checked": null
          },
          {
              "menuId": 61,
              "parentId": 1,
              "title": "个人中心",
              "path": "/user",
              "component": null,
              "menuType": 0,
              "sortNumber": 11,
              "authority": null,
              "icon": "Tickets",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:09:54",
              "updateTime": "2024-11-01 10:17:30",
              "children": null,
              "checked": null
          },
          {
              "menuId": 130,
              "parentId": 0,
              "title": "数据管理",
              "path": "/data",
              "component": null,
              "menuType": 0,
              "sortNumber": 20,
              "authority": null,
              "icon": "Coin",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-11 21:24:12",
              "updateTime": "2024-10-14 00:26:27",
              "children": null,
              "checked": null
          },
          {
              "menuId": 99,
              "parentId": 0,
              "title": "套餐管理",
              "path": "/vip",
              "component": "",
              "menuType": 0,
              "sortNumber": 30,
              "authority": null,
              "icon": "Ticket",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:15:18",
              "updateTime": "2024-10-14 00:27:15",
              "children": null,
              "checked": null
          },
          {
              "menuId": 101,
              "parentId": 0,
              "title": "订单管理",
              "path": "/order",
              "component": "",
              "menuType": 0,
              "sortNumber": 40,
              "authority": "",
              "icon": "Handbag",
              "hide": 0,
              "meta": null,
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2021-02-02 20:15:18",
              "updateTime": "2024-10-14 00:34:50",
              "children": null,
              "checked": null
          },
          {
              "menuId": 163,
              "parentId": 0,
              "title": "模板与插件",
              "path": "/templateplugin",
              "component": "",
              "menuType": 0,
              "sortNumber": 40,
              "authority": "",
              "icon": "Orange",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:52:18",
              "updateTime": "2024-10-14 00:52:18",
              "children": null,
              "checked": null
          },
          {
              "menuId": 152,
              "parentId": 0,
              "title": "笔记公开",
              "path": "/release",
              "component": "",
              "menuType": 0,
              "sortNumber": 50,
              "authority": "",
              "icon": "Upload",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-13 23:05:22",
              "updateTime": "2024-10-14 00:57:23",
              "children": null,
              "checked": null
          },
          {
              "menuId": 157,
              "parentId": 0,
              "title": "报告与反馈",
              "path": "/feedback",
              "component": "",
              "menuType": 0,
              "sortNumber": 60,
              "authority": "",
              "icon": "WarnTriangleFilled",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:14:56",
              "updateTime": "2024-10-14 01:05:46",
              "children": null,
              "checked": null
          },
          {
              "menuId": 154,
              "parentId": 0,
              "title": "隐私政策",
              "path": "/term",
              "component": "",
              "menuType": 0,
              "sortNumber": 300,
              "authority": "",
              "icon": "Warning",
              "hide": 0,
              "meta": "",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2024-10-14 00:12:17",
              "updateTime": "2024-10-14 00:39:59",
              "children": null,
              "checked": null
          },
          {
              "menuId": 1,
              "parentId": 0,
              "title": "系统管理",
              "path": "/system",
              "component": null,
              "menuType": 0,
              "sortNumber": 500,
              "authority": null,
              "icon": "Setting",
              "hide": 0,
              "meta": "{\"badge\": \"New\", \"badgeColor\": \"warning\"}",
              "deleted": 0,
              "tenantId": 1,
              "createTime": "2020-02-26 12:51:23",
              "updateTime": "2024-10-14 00:19:14",
              "children": null,
              "checked": null
          }
      ],
      "enabled": true,
      "accountNonExpired": true,
      "credentialsNonExpired": true,
      "accountNonLocked": true
  };
  }
  return Promise.reject(new Error(res.data.message));
}

/**
 * 修改当前登录用户的密码
 */
export async function updatePassword(data) {
  const res = await request.put('/auth/password', data);
  if (res.data.code === 0) {
    return res.data.message ?? '修改成功';
  }
  return Promise.reject(new Error(res.data.message));
}

/**
 * 修改当前登录用户的个人信息
 */
export async function updateUserInfo(data) {
  const res = await request.put('/auth/user', data);
  if (res.data.code === 0 && res.data.data) {
    return res.data.data;
  }
  return Promise.reject(new Error(res.data.message));
}
